version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/knightfam

hooks:
  BeforeInstall:
    - location: scripts/stop-container.sh  # 🛑 Make sure name matches actual file!
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start-container.sh  # ✅ Consistent with Script 3
      timeout: 60
      runas: ec2-user

