spring:
  application:
    name: knightfam

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://knightfamdb2.c7y0y42uc2st.us-east-2.rds.amazonaws.com:5432/knightfam"
    username: "famknight"
    password: "banjo123"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 1eddhu1oale604stl9e348bq0i     #${COGNITO_CLIENT_ID:placeholder}
            client-secret: 1jv782dl6h69u2qaq4phu9jvt3sniottlp7otj9qh9skavi472rc    #${COGNITO_CLIENT_SECRET:placeholder}
            provider: cognito
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          cognito:
             issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_4L2Pj9fxk

logging:
  level:
    org.springframework.security: DEBUG

cognito:
  domain: "https://us-east-24l2pj9fxk.auth.us-east-2.amazoncognito.com"
  logout-redirect-url: "http://localhost:8080/"

aws:
  s3:
    bucket: knightfam-s3
    region: us-east-2
